# Task 6 - Naive Bayes
## Target column - InternetService

    All imports

In [1]:
import pandas as pd
import numpy as np

from collections import OrderedDict
from functools import reduce
from operator import mul

from sklearn.model_selection import train_test_split

#Naive Bayes models
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

    Load the selected Data Set.
    

In [2]:
dataset = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

#Edit dataset for iterable
dataset = dataset.drop(columns=['customerID'])
dataset['gender'] = dataset['gender'].map({'Female': 0, 'Male': 1})
dataset['Partner'] = dataset['Partner'].map({'Yes': 1, 'No': 0})
dataset['Dependents'] = dataset['Dependents'].map({'Yes': 0, 'No': 1})
dataset['PhoneService'] = dataset['PhoneService'].map({'Yes': 0, 'No': 1})
dataset['MultipleLines'] = dataset['MultipleLines'].map({'Yes': 1, 'No': 0, 'No phone service': 2})
dataset['InternetService'] = dataset['InternetService'].map({'DSL': 1, 'No': 0, 'Fiber optic': 2})
dataset['OnlineSecurity'] = dataset['OnlineSecurity'].map({'Yes': 1, 'No': 0, 'No internet service': 2})
dataset['OnlineBackup'] = dataset['OnlineBackup'].map({'Yes': 1, 'No': 0, 'No internet service': 2})
dataset['DeviceProtection'] = dataset['DeviceProtection'].map({'Yes': 1, 'No': 0, 'No internet service': 2})
dataset['TechSupport'] = dataset['TechSupport'].map({'Yes': 1, 'No': 0, 'No internet service': 2})
dataset['StreamingTV'] = dataset['StreamingTV'].map({'Yes': 1, 'No': 0, 'No internet service': 2})
dataset['StreamingMovies'] = dataset['StreamingMovies'].map({'Yes': 1, 'No': 0, 'No internet service': 2})
dataset['Contract'] = dataset['Contract'].map({'Two year': 1, 'Month-to-month': 0, 'One year': 2})
dataset['PaperlessBilling'] = dataset['PaperlessBilling'].map({'Yes': 1, 'No': 0})
dataset['PaymentMethod'] = dataset['PaymentMethod'].map({'Electronic check': 1, 'Mailed check': 0, 'Bank transfer (automatic)': 2, 'Credit card (automatic)': 3})
dataset['Churn'] = dataset['Churn'].map({'Yes': 1, 'No': 0})
dataset['TotalCharges'] = dataset['TotalCharges'].apply(func=lambda x: 0 if x == ' ' else float(x))
#print(dataset['TotalCharges'].value_counts())
#dataset
corr = dataset.corr()

# 'Correlation analis for found target column'
#series = pd.Series()
#for i, c in enumerate(corr):
#    series = series.add(pd.Series({f'{corr[c].abs().nlargest(2).index[1]}{i}': corr[c].abs().nlargest(2).iloc[1]}), fill_value=0)
#    print(corr[c].abs().nlargest(2))
#corr['Churn'].abs().nlargest(2)[1:]
#series = series.apply(func=lambda x: float(x))
#series.nlargest(3) #Target column is InternetService

#dataset

    Split the data set into the train and test set.

In [3]:
X = dataset.drop(columns=['InternetService'])
y = dataset['InternetService']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    - Create an instance of Gaussian Naive Bayes
    - Create an instance of Multinomial Naive Bayes
    - Create an instance of Bernoulli Naive Bayes

In [4]:
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

    Train every version of Naive Bayes on the train data set and make predictions on the corresponding test subsets.

In [5]:
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

clf1_predict = clf1.predict(X_test)
clf2_predict = clf2.predict(X_test)
clf3_predict = clf3.predict(X_test)

print(clf1_predict)
print(clf2_predict)
print(clf3_predict)

[1 0 0 ... 1 2 1]
[0 0 0 ... 1 2 1]
[1 0 0 ... 1 2 1]


    Get the accuracy of model.


In [6]:
clf1_accuracy = clf1.score(X_test, y_test)
clf2_accuracy = clf2.score(X_test, y_test)
clf3_accuracy = clf3.score(X_test, y_test)

accuracy = pd.DataFrame([
                         ['GaussianNB', clf1_accuracy],
                         ['MultinomialNB', clf2_accuracy],
                         ['BernoulliNB', clf3_accuracy]
                         ], 
                        columns=['ML Model', 'Accuracy'])

accuracy

ML Model  Accuracy
0     GaussianNB  0.911500
1  MultinomialNB  0.810696
2    BernoulliNB  0.813535

    Make a conclusion based on the data frame that you got.


## Concluzia mea in baza DataFrame-ului care l-am primit cu acuratetia fiecarei din ML consta in ceea ca ceea mai buna predictie din toate a dat Gaussian Naive Bayes si, cu mult, 10% mai bine de cat celelalte. Dar care e diferenta nu cam stiu